


export enum ZombieAction {
    NORMAL_BEHAVIOR,
    NORMAL_BEHAVIOR_IN_DOORS,
    CHASING_PLAYER_OUT_SIDE,
    CHASING_PLAYER_IN_DOORS,
    DETECTED_PLAYER,
    FACING_WINDOW,
    FACING_DOOR,
    NO_ACTION
}